### PR TITLE
Fix staled Twitter icon

### PR DESCRIPTION
**Pull request by tiagogalvao**
## Description
Updating references from "Twitter" to "X"

## Motivation and Context
Twitter rebranding

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Visual changes only

## Checklist:
Every twitter reference should show the new logo and reference "X" instead of "Twitter"

### CODE REVIEW

**Comment by janosdebugs** [comment]
Hey @tiagogalvao thank you very much! Unfortunately, your commit is not signed off. Please use `git commit -s --amend` to sign off your commit, followed by a `git push --force`.

**Comment by tiagogalvao** [comment]
@janosdebugs I hope it is fine now. Thank you.

**Review by janosdebugs — APPROVED** [review]
Thank you!

**Comment by janosdebugs** [comment]
Hey @tiagogalvao sorry to ping you again, it seems there was an oversight on our part and we forgot to add a license file to the repository. Would you mind using the review feature to sign off on the PR #272 please?

**Comment by tiagogalvao** [comment]
No worries! Just did it.

**Pull request merged**
