### PR TITLE
Upgrade to Docusaurus v3.1

### PR DESCRIPTION
**Pull request by damianstasik**
- upgrades Docusaurus, React, MDX and TS to latest version
- upgraded everything that had a new major version
- ~~everything works except the 3rd-party search~~ Edit: Thanks to Algolia we now also have working search!

~~Would be nice to have it if we could replace the current search with Algolia~~ Edit: Done!

### CODE REVIEW

**Comment by damianstasik** [comment]
There's also a slight reduction in the bundle size, which is always welcome.

**Comment by damianstasik** [comment]
Please help me test this PR, overall it looks okay, everything is working as expected.

**Comment by janosdebugs** [comment]
As discussed, I'll take a look at this once my other docs issues are merged (E.T.A. next week)

**Review by janosdebugs — APPROVED** [review]
Looks good to me, the only difference is the color of the code blocks.

**Review by Yantrio — APPROVED** [review]

**Pull request merged**
