### PR TITLE
fix: changed the staled twitter icon

### PR DESCRIPTION
**Pull request by Dev79844**
## Description
Replaced the old twitter icon to new twitter icon

## Motivation and Context
The motive was to change the old twitter icon to new one

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change depends on a change in the main [opentofu repository](https://github.com/opentofu/opentofu).

### CODE REVIEW

**Review by janosdebugs — APPROVED** [review]
Looks good, thank you!

**Comment by janosdebugs** [comment]
Side note, the mobile menu still says "Twitter" 
image

**Review by janosdebugs — CHANGES_REQUESTED** [review]
Sorry to retract my approval, but I believe the word "twitter" should also be changed everywhere on the website accordingly, including in the configuration.

**Comment by ebel** [comment]
FWIW https://github.com/opentofu/opentofu/issues/1028 is related.

**Review by janosdebugs — CHANGES_REQUESTED** [review]
Sorry for the delay, the changes look good, but there seems to be some unrelated stuff in there. Could you please remove those?

**Comment by janosdebugs** [comment]
Thank you for your work, this is now resolved. Closing in favor of #267

**Pull request closed without merging**
