### PR TITLE
Syntax-highlight PowerShell code snippets

### PR DESCRIPTION
**Pull request by xuoe**
## Description
This enables syntax-highlighting for PowerShell snippets, one of which is included at https://opentofu.org/docs/intro/install/portable, the Windows tab.

## Screenshots (if appropriate):
| Before | After |
| ------ | ----- |
| Before | After |

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change depends on a change in the main [opentofu repository](https://github.com/opentofu/opentofu).

### CODE REVIEW

**Comment by janosdebugs** [comment]
Hey @xuoe thank you for catching this, I'll test it tomorrow morning CET.

**Review by janosdebugs — APPROVED** [review]
My apologies for the delay @xuoe, I tested it and it works as intended. Thank you very much for your contribution.

**Review by cube2222 — APPROVED** [review]

**Review by Yantrio — APPROVED** [review]

**Comment by janosdebugs** [comment]
Hey @xuoe sorry to ping you again, it seems there was an oversight on our part and we forgot to add the license file to this repository. Would you mind using the review function to sign off on the PR #272 please?

**Comment by xuoe** [comment]
Sure thing. Just need to be requested a review.

**Pull request merged**
